name: "NextDNS Add-on"
description: "Run a NextDNS DNS-over-HTTPS (DoH) client using a Home Assistant Add-on."
version: "1.0"
slug: "nextdns_addon"
arch:
  - amd64
  - armv7
  - arm64
startup: "services"
boot: "auto"
ports:
  53/udp: 53
  53/tcp: 53
options:
  config_id: "9a15c6"
  listen: "0.0.0.0:53"
  log_level: "info"
schema:
  config_id: str
  listen: str
  log_level:
    type: string
    choices:
      - "debug"
      - "info"
      - "warn"
      - "error"
      - "fatal"
